config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lendings
  get "dashboards/index"
  # Sidekiq::Web.use Rack::Auth::Basic, "Protected Area" do |email, password|
  #   email == "admin@gmail.com" && password == "password" # Replace with secure credentials
  # end
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "dashboards#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lending.rb
class Lending < ApplicationRecord
  belongs_to :user
  enum state:{requested: 0,approved: 1,open: 2,closed: 3, rejected: 4, waiting_for_adj_acceptance: 5, readjusment_requested: 6 }
  def self.ransackable_attributes(auth_object = nil)
    ["amount", "interest_rate", "state", "user_id"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable   
  enum role: { admin: 0,customer: 1}
  has_many :lendings
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "name", "remember_created_at", "reset_password_sent_at",              "reset_password_token", "role", "updated_at", "wallet"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController

  before_action :authenticate_user!
  def index
    @lendings=current_user.lendings

  end

  def show
    @lending=Lending.find(params[:id])
  end

  def new
    @lending=Lending.new
  end

  def create
    @lending = current_user.lendings.new(lending_params)
    if @lending.save
      redirect_to lendings_path, notice: 'Loan request was successfully created.'
    else
      render :new
    end
  end

  def edit
    @lending=Lending.find(params[:id])
  end

  def update
    @lending=Lending.find(params[:id])
    @admin_user = AdminUser.first
    @user=current_user
    if params[:state] == "confirm"
      @lending.update(state: "open")
      flash[:notice] = "Loan state changed to Open." 
      @admin_user.update(wallet: @admin_user.wallet - @lending.amount) 
      CalInterestRateJob.perform_at(10.seconds.from_now)
      @user.update(wallet:@user.wallet+@lending.amount)
    elsif params[:state] == "reject"
      @lending.update(state: "rejected")
      flash[:notice] = "Loan state changed to Rejected."
    else
      @lending.update(state: "closed")
      flash[:notice] = "Loan is paid." 
      @user.update(wallet:@user.wallet-(@lending.amount+@lending.simple_interest) )
      @admin_user.update(wallet:@admin_user.wallet+(@lending.amount+@lending.simple_interest) )
    end  
    if @lending.update(lending_params)
      redirect_to lendings_path, notice: 'Lending money was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lending=Lending.find(params[:id])
    @lending.destroy
    redirect_to lendings_path, notice: 'Lending money was successfully destroyed.'
  end
  
  private
  def lending_params
    params.require(:lending).permit(:amount, :interest_rate)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/dashboards/index.html.erb
<%= render partial: "partial/header" %>
#<%button_to 'Know More'%>

<% if user_signed_in?%> 
 <h1> Customer Dashboard<h1>
 <%= button_to 'Apply for loan', new_lending_path, method: :get, class:"btn-logout"%>
  <%= button_to 'View all loan', lendings_path, method: :get, class:"btn-logout"%>
  <%else%>
  <p>welcome to <h1>lending money app</h1><p>
  <p>Your Financial Bridge to Instant Solutions!</p>
  <p>apply easy loans and manage your interest rate </p>
 <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lending Money" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if flash[:notice] %>
  <div class="flash flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lendings/_form.html.erb
<%= form_with model: lending do |form|%>
  <%= form.label :amount%>
  <%= form.number_field :amount%>
  <%= form.label :interest_rate %>
  <%= form.number_field :interest_rate %>
  <%= form.submit %>
<%end%>
  


  

app/views/lendings/create.html.erb
<h1>Lendings#create</h1>
<p>Find me in app/views/lendings/create.html.erb</p>

app/views/lendings/edit.html.erb
<h1>Lendings#edit</h1>
<p>Find me in app/views/lendings/edit.html.erb</p>

app/views/lendings/index.html.erb
<%= render partial:"partial/header"%>
<h1>Your Loans</h1>
<table>
  <thead>
    <tr>
      <th>Loan Id</th>
      <th>Loan Amount</th>
      <th>Loan Rate</th>
      <th>Loan State</th>
    </tr>
  </thead>
  <tbody>
 
    <% @lendings.each do |lending| %>

      <tr>
        <td><%= lending.id %></td>
        <td><%= lending.amount %></td>
        <td><%= lending.interest_rate %>%</td>
        <td><%= lending.state %></td>
      <% if lending.state == "approved" %>
      <td>  <%= button_to "Confirm", lending_path(lending, state: "confirm"), method: :patch, class: "btn btn-success" %>
        <%= button_to "Reject", lending_path(lending, state: "reject"), method: :patch, class: "btn btn-danger" %>
      <% end %> 
          <% if lending.state == "open" %>
      <td>  <%= button_to "Pay Now", lending_path(lending, state: "pay"), method: :patch, class: "btn btn-success" %>
      <% end %> 
      </td> 
      </tr>
    <%  end %>


  </tbody>
</table>

<%= button_to "New Loan Apply", new_lending_path, method: :get, class: "btn-new-loan" %>

app/views/lendings/new.html.erb
<%= render "form" , lending: @lending%>

app/views/lendings/show.html.erb
<h1>Lendings#show</h1>
<p>Find me in app/views/lendings/show.html.erb</p>

app/views/partial/_header.html.erb
<nav class="navbar">
    <div class="navbar-left">
      <h1 class="navbar-title">LOAN APP</h1>
    </div>
     <div class="navbar-right">
      <% if user_signed_in?%>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class:"btn-logout"%>
      <%else%>
              <%= button_to 'Sign in', new_user_registration_path, method: :get, class: "btn-logout" %>
            <%= button_to 'Log in', new_user_session_path, method: :get, class: "btn-logout" %>
            <%= button_to 'Log in Admin', admin_user_session_path, method: :get, class: "btn-logout" %>
      <%end%>
      </div>
  </nav>